[package]
name = "inquisition"
version = "0.0.1"
authors = ["Lutetium Vanadium"]
edition = "2018"

[workspace]
members = [
    ".",
    "ui",
]

[dependencies]
ahash = { version = "0.7.2", optional = true }
crossterm = "0.19.0"
tempfile = "3"
ui = { path = "./ui" }

[features]
default = ["fast-hash"]
fast-hash = ["ahash"]
