[package]
name = "inquisition"
version = "0.0.1"
authors = ["Lutetium Vanadium"]
edition = "2018"

[workspace]
members = [
    ".",
    "inquisition-ui"
]

[dependencies]
tempfile = "3"
atty = "0.2"
ui = { package = "inquisition-ui", path = "./inquisition-ui" }

ahash = { version = "0.7", optional = true }
async-trait = { version = "0.1", optional = true }
futures = { version = "0.3", optional = true }

# The following dependencies are renamed in the form `<dep-name>-dep` to allow
# a feature name with the same name to be present. This is necessary since
# these features are required to enable other dependencies
smol-dep = { package = "smol", version = "1.2", optional = true }
tokio-dep = { package = "tokio", version = "1.5", optional = true, features = ["fs", "process", "io-util"] }
async-std-dep = { package = "async-std", version = "1.9", optional = true, features = ["unstable"] }

[features]
default = ["crossterm", "ahash"]
crossterm = ["ui/crossterm"]
termion = ["ui/termion"]
tokio = ["tokio-dep", "async-trait", "ui/tokio"]
smol = ["smol-dep", "async-trait", "ui/smol"]
async-std = ["async-std-dep", "async-trait", "ui/async-std"]
