[package]
name = "discourse"
version = "0.0.1"
authors = ["Lutetium Vanadium"]
edition = "2018"

[workspace]
members = [
    ".",
    "discourse-ui",
    "discourse-macros",
]

[dependencies]
tempfile = "3"
atty = "0.2"
ui = { package = "discourse-ui", path = "./discourse-ui" }
macros = { package = "discourse-macros", path = "./discourse-macros" }

ahash = { version = "0.7", optional = true }

[dev-dependencies]
trybuild = { version = "1.0.42", features = ["diff"] }
csscolorparser = "0.4"  # examples/input.rs
regex = "1.5"           # examples/prompt_module.rs
fuzzy-matcher = "0.3"   # examples/file.rs

[features]
default = ["crossterm", "ahash"]
crossterm = ["ui/crossterm"]
termion = ["ui/termion"]
