[package]
name = "inquisition"
version = "0.0.1"
authors = ["Lutetium Vanadium"]
edition = "2018"

[workspace]
members = [
    ".",
    "inquisition-ui",
    "inquisition-macros",
]

[dependencies]
tempfile = "3"
atty = "0.2"
ui = { package = "inquisition-ui", path = "./inquisition-ui" }
macros = { package = "inquisition-macros", path = "./inquisition-macros" }

ahash = { version = "0.7", optional = true }

[dev-dependencies]
trybuild = "1.0.42"
csscolorparser = "0.4" # examples/input.rs
regex = "1.5"          # examples/prompt_module.rs

[features]
default = ["crossterm", "ahash"]
crossterm = ["ui/crossterm"]
termion = ["ui/termion"]
