[package]
name = "inquisition"
version = "0.1.0"
authors = ["Lutetium Vanadium"]
edition = "2018"

[workspace]
members = [
    ".",
    "ui",
]

[dependencies]
ahash = "0.7.2"
crossterm = "0.19.0"
tempfile = "3"
ui = { path = "./ui" }
