[package]
name = "inquisition-ui"
version = "0.0.1"
authors = ["Lutetium Vanadium"]
edition = "2018"

[dependencies]
bitflags = "1.2"
textwrap = "0.13"
unicode-segmentation = "1.7"

crossterm = { version = "0.19", optional = true }
termion = { version = "1.5", optional = true }
