name: Async std

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy --verbose --features=async-std --bins --examples
    - name: Run tests
      run: cargo test --workspace --verbose --features=async-std
