name: Termion

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy --verbose --no-default-features --features=termion --bins --examples
    - name: Run tests
      run: cargo test --workspace --verbose --no-default-features --features=termion -- --include-ignored
